# From: https://github.com/cpp-best-practices/cmake_template
additional_commands:
  foo:
    flags:
    - BAR
    - BAZ
    kwargs:
      DEPENDS: '*'
      HEADERS: '*'
      SOURCES: '*'
bullet_char: '*'
dangle_parens: true
enum_char: .
line_ending: unix
line_width: 120
max_pargs_hwrap: 3
separate_ctrl_name_with_space: false
separate_fn_name_with_space: false
tab_size: 2
autosort: true

markup:
  enable_markup: false

lint:
  disabled_codes: [C0307, W0105, C0111, E1126]

